/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetdysgraphie;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author crouvera
 */
public class DeuxiemePage extends javax.swing.JFrame implements ActionListener{

    private Trace modele;
    private Trace essai;
    /**
     * Creates new form NewJFrame
     */
    public DeuxiemePage(Trace tModele) {
        initComponents();
        jLabel2.setVisible(false);
        modele=tModele;
        
        //choix du ficher à observer
        chargerFichier();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        boutonRecommencer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelTrace = new javax.swing.JPanel();
        panelAccel = new javax.swing.JPanel();

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(null);

        boutonRecommencer.setFont(new java.awt.Font("French Script MT", 0, 18)); // NOI18N
        boutonRecommencer.setText("Recommencer");
        boutonRecommencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonRecommencerActionPerformed(evt);
            }
        });
        getContentPane().add(boutonRecommencer);
        boutonRecommencer.setBounds(850, 440, 110, 29);

        jLabel1.setFont(new java.awt.Font("French Script MT", 0, 24)); // NOI18N
        jLabel1.setText("Entraîne-toi : ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(430, 30, 220, 100);

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(660, 520, 70, 60);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(660, 350, 60, 60);

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(660, 430, 60, 60);

        jLabel5.setFont(new java.awt.Font("French Script MT", 0, 24)); // NOI18N
        jLabel5.setText("L'accélération de ton mouvement : ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 330, 320, 90);

        panelTrace.setPreferredSize(new java.awt.Dimension(649, 229));
        getContentPane().add(panelTrace);
        panelTrace.setBounds(120, 100, 860, 200);

        panelAccel.setPreferredSize(new java.awt.Dimension(0, 87));
        getContentPane().add(panelAccel);
        panelAccel.setBounds(70, 390, 370, 170);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void boutonRecommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonRecommencerActionPerformed
        // TODO add your handling code here:
        //jLabel2.setVisible(true);
        chargerFichier();
    }//GEN-LAST:event_boutonRecommencerActionPerformed

    public void chargerFichier(){
        JFileChooser f = new JFileChooser();
        int result = f.showOpenDialog(this);
        if(result == JFileChooser.APPROVE_OPTION){
            File fichier = f.getSelectedFile();
            try {
                essai = new Trace(fichier);
                afficherGraphs();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "fichier : "+fichier.getAbsolutePath()+" introuvable");
            }
        }
    }
    
    public void afficherGraphs(){
        JPanel ca = new Courbe(essai.getPointsAcceleration());
        panelAccel.removeAll();
        panelAccel.setSize(panelAccel.getPreferredSize());
        ca.setSize(panelAccel.getSize());
        panelAccel.add(ca);
        
        JPanel c = new Courbe(essai);
        panelTrace.removeAll();
        panelTrace.setSize(panelTrace.getPreferredSize());
        c.setSize(panelTrace.getSize());
        panelTrace.add(c);
        
        panelAccel.setVisible(true);
        panelTrace.setVisible(true);
        this.pack();
        revalidate();
        repaint();
        
        System.out.println(modele.getNbPic());
        System.out.println(essai.getNbPic());
        
        System.out.println(modele.estSimilaireAuModele(essai));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonRecommencer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panelAccel;
    private javax.swing.JPanel panelTrace;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
